/* DO NOT EDIT THIS FILE - it is machine generated */
# include "demo_aspectjdemo_JNIAlgorithm.h"
//JNI标识 返回值类型       包名+类名+方法名
 JNIEXPORT jint JNICALL Java_demo_aspectjdemo_JNIAlgorithm_sum(JNIEnv *env, jclass a, jint num1, jint num2){
    return num1+num2;
 }