/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_aspectjdemo_MathKit */

#ifndef _Included_demo_aspectjdemo_MathKit
#define _Included_demo_aspectjdemo_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_aspectjdemo_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_demo_aspectjdemo_MathKit_square
  (JNIEnv *, jint);

#ifdef __cplusplus
}
#endif
#endif
